### ISSUE TITLE
Issue show double popup

### ISSUE THREAD

**Issue by trungkienpvt** [dwainscheeren/dwains-lovelace-dashboard#623] opened 2022-09-15 09:01 UTC
Hi @dwainscheeren ,
I have found out an issue with popup on Dwains Dashboard. When I add new popup to my card on dashboard, and then click on it will show double popup like image 
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/2033854/190362016-62ce8c55-8d34-49b8-b71b-a918b1fbeeed.png">
It happend on Hass 2022.9.2 and lastest browser mod integrated. Hope you can recheck and fix it. Thanks you so much

**Comment by dwainscheeren** [comment] 2022-09-15 09:34
Duplicate of #619

**Closed as completed by dwainscheeren** 2022-09-15 09:34 UTC
