### ISSUE TITLE
slow and error on Home Assistant 2023.9.2

### ISSUE THREAD

**Issue by dtavnn** [dwainscheeren/dwains-lovelace-dashboard#729] opened 2023-09-20 13:20 UTC
![dsfsd](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/14801642/8738d27d-e2bf-4456-80d5-096701f8fd8a)

dwains-lovelace-dashboard v3.4.3 displays slowly and sometimes has errors like the image above.

**Comment by mjb83** [comment] 2023-09-21 21:11
Seconded, same error. Is this no longer supported? Too bad I loved the automatic card creation.

**Comment by dwainscheeren** [comment] 2023-09-22 05:59
Duplicate of #726

**Closed as completed by dwainscheeren** 2023-09-22 05:59 UTC
