### ISSUE TITLE
"Unknown error" while loading dashboard in HA 2022.03

### ISSUE THREAD

**Issue by ElyFNV** [dwainscheeren/dwains-lovelace-dashboard#419] opened 2022-03-03 10:11 UTC
As the title says, after updating HA to the version 2022.03, the Dwains Dashboard can't load anymore and it only says "Unknown Error".
Due to the change to material from paper elements from the latest HA update (2022.03) the Ul components have be broken.
Dwain are you up to a solution? I love your dashboard!!!
I can't live without it! Please fix It!
Thanks!!

**Comment by ElyFNV** [comment] 2022-03-03 20:43
Why to him it works? "https://www.reddit.com/r/homeassistant/comments/t5ff38/dwains_dashboard_and_ha_202203/hz892r6/?context=3"

**Comment by confucius78** [comment] 2022-03-04 08:46
I see the same, however reloading does resolve the issue

**Comment by ElyFNV** [comment] 2022-03-04 09:06
I've tried everything. Reloading, deleting cache, uninstalling and reinstalling it. Always same error. I don't know what to do.
I installed Dwains Dashboard through HACS... It worked until I update HA to versione 2022.03

**Comment by dwainscheeren** [comment] 2022-03-04 09:57
Then downgrade HA to 2022.2

**Comment by ElyFNV** [comment] 2022-03-04 10:12
I just tried to downgrade the home assistant core to version 2022.2.9. Of course, absolutely nothing has changed! But noticed that the frontend version is still 20220203, even after the core downgrade!!! And that's the one in my opinion that create the issue! In fact, the problem is something graphic!
However I don't know how ti downgrade frontend version.

**Comment by Piti8576** [comment] 2022-03-04 19:11
Same Problem. Can wait for update/fix.

**Comment by ElyFNV** [comment] 2022-03-06 00:56
So ... I really tried them all and nothing seemed to work.  In the end I realized that the problem was not in reinstalling the integration itself, but in the files inside the "config/dwains_dashboard" folder. 
In other words, all those basic configuration files that must be modified at the very first start. In fact, if you try to delete those files (found in config/dwains_dashboard) and then perform a reinstall of the integration, you will see that the "unknown error Reload UI" error disappears.
After doing all this go to the terminal and issue the following command: "ha core update --version = 2022.2.9".
Wait for Home Assistant to downgrade to core version 2022.2.9.  Then, only when you have downgraded, reinstall the Dwains Dashboard integration.  At that point you can safely reconfigure the files inside the "config/dwains-dashboard" folder.  And as if by magic everything will work again.

**Comment by rananna** [comment] 2022-03-07 01:44
Has any progress been made on identifying root cause?
Is a fix being developed?

**Comment by rananna** [comment] 2022-03-10 09:01
Is no one else seeing this issue?

**Comment by ElyFNV** [comment] 2022-03-10 09:48
Try to open a new one talking about the same problem.
This, despite being a very serious problem that prevents you from using the dashboard after the update to HA 2022.03, does not seem to be very considered ...

**Comment by dwainscheeren** [comment] 2022-03-10 12:20
As far as I know DD works well on 2022.3

**Comment by confucius78** [comment] 2022-03-10 12:29
I can confirm seeing some issues (seemingly at random) when loading DD, which are in my case easily fixed by reloading. This however only works on mobile (ios) by pulling down. I have encountered this issue on pc and could bot resolve it.

In my case, all elements are shown as error

**Comment by rkotulan** [comment] 2022-03-10 12:39
Work well in latest version 2022.3.3

**Comment by dwainscheeren** [comment] 2022-03-10 12:40
Try installing button-card in hacs then do a ctrl + f5 to clear cache.

**Comment by rananna** [comment] 2022-03-10 12:41
This is what I see upon upgrading

**Comment by rananna** [comment] 2022-03-10 12:43
Installing button card with hacs solved the problem!
Thank you.

**Comment by ElyFNV** [comment] 2022-03-15 14:07
If you are on Windows try reloading with CTRL+F5. And be sure to have installed the Custom Button Card from HACS.

**Comment by lbouriez** [comment] 2022-03-21 16:25
Related: https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues/422

**Comment by lbouriez** [comment] 2022-03-21 16:31
> Try installing button-card in hacs then do a ctrl + f5 to clear cache.

This fixed my issue on the mobile application, Installing the button-card.

**Comment by mjpblaauw** [comment] 2022-03-22 08:16
Worked! and problem solved! Installed the button-card via HACS

**Comment by Twanne** [comment] 2022-03-31 07:06
still on this issue. the button card is installed, but I get another message stating the following:

Logger: frontend.js.latest.202203012
Source: components/system_log/__init__.py:190
First occurred: March 30, 2022, 17:55:51 (6 occurrences)
Last logged: 09:02:54

https://IP_ADDRESS/dwains_dashboard/js/dwains-dashboard.js:90:13832 Uncaught TypeError: Cannot read properties of undefined (reading 'popup_cards')

**Comment by dwainscheeren** [comment] 2022-03-31 08:07
You can ignore that error.

**Closed by dwainscheeren** 2022-03-31 08:07 UTC

**Comment by smibrandon** [comment] 2022-06-14 14:27
Receiving the same "Unknown Error". I've tried all the troubleshooting in this thread, and nothing. Tried a different device, still getting the same error.

Home Assistant OS 8.1 // core-2022.6.3
