### ISSUE TITLE
Error loading on beta 2023.12.0b0 AttributeError: module 'homeassistant.util.yaml.loader' has no attribute 'SafeLineLoader'

### ISSUE THREAD

**Issue by FrancoLoco** [dwainscheeren/dwains-lovelace-dashboard#753] opened 2023-11-30 02:12 UTC
AttributeError: module 'homeassistant.util.yaml.loader' has no attribute 'SafeLineLoader'

Issue with [#103609](https://github.com/home-assistant/core/pull/103609) the SafeLineLoader -> PythonSafeLoader rename.

--
Log details (ERROR)
Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 20:51:48 (2 occurrences)
Last logged: 20:54:09

  File "/usr/src/homeassistant/homeassistant/config.py", line 439, in async_hass_config_yaml
    config = await hass.loop.run_in_executor(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config.py", line 470, in load_yaml_config_file
    conf_dict = load_yaml(config_path, secrets)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 155, in load_yaml
    return parse_yaml(conf_file, secrets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 168, in parse_yaml
    return _parse_yaml(FastSafeLoader, content, secrets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 198, in _parse_yaml
    yaml.load(content, Loader=lambda stream: loader(stream, secrets))  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 330, in _handle_mapping_tag
    nodes = loader.construct_pairs(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 330, in _handle_mapping_tag
    nodes = loader.construct_pairs(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 249, in _include_yaml
    return _add_reference(load_yaml(fname, loader.secrets), loader, node)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dwains_dashboard/process_yaml.py", line 46, in load_yamll
    return loader.yaml.load(config_file, Loader=lambda stream: loader.SafeLineLoader(stream, secrets)) or OrderedDict()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
             ^^^^^^^^^^^^^^
  File "/config/custom_components/dwains_dashboard/process_yaml.py", line 46, in <lambda>
    return loader.yaml.load(config_file, Loader=lambda stream: loader.SafeLineLoader(stream, secrets)) or OrderedDict()
                                                               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.util.yaml.loader' has no attribute 'SafeLineLoader'

**Comment by Lampornis** [comment] 2023-12-02 18:48
I also have his issue.  In addition this error kills all my devices running in Z2M (I suspect because of the mqtt error referenced above).

**Comment by Lampornis** [comment] 2023-12-04 13:56
This problem appears to have been resolved in 2023.12.0b1.

**Comment by FrancoLoco** [comment] 2023-12-04 14:00
> This problem appears to have been resolved in 2023.12.0b1.

Yes but I think they only patched it temporarily, delaying the breaking change for later..

**Comment by FrancoLoco** [comment] 2023-12-04 16:51
> > This problem appears to have been resolved in 2023.12.0b1.
> 
> Yes but I think they only patched it temporarily, delaying the breaking change for later..

Yes it is broken again in 2023.12.0b2.

Here are the logs

2023-12-04 11:46:29.554 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.dwains_dashboard
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 814, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/dwains_dashboard/__init__.py", line 10, in <module>
    from .process_yaml import process_yaml, reload_configuration
  File "/config/custom_components/dwains_dashboard/process_yaml.py", line 69, in <module>
    loader.SafeLineLoader.add_constructor("!include", _include_yaml)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'add_constructor'
2023-12-04 11:46:29.569 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'dwains_dashboard': Unable to import component: Exception importing custom_components.dwains_dashboard
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 814, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/dwains_dashboard/__init__.py", line 10, in <module>
    from .process_yaml import process_yaml, reload_configuration
  File "/config/custom_components/dwains_dashboard/process_yaml.py", line 69, in <module>
    loader.SafeLineLoader.add_constructor("!include", _include_yaml)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'add_constructor'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.dwains_dashboard
q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+rest%22
2023-12-04 11:46:44.968 WARNING (SyncWorker_8) [homeassistant.util.yaml.loader] SafeLineLoader was called from dwains_dashboard, this is a deprecated class. Use PythonSafeLoader instead, please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+dwains_dashboard%22

**Comment by Lampornis** [comment] 2023-12-04 17:09
Thanks for the warning.  Hope this gets addressed before the official release Wednesday.

**Comment by FSHelgeland** [comment] 2023-12-04 22:08
Didnt see this warning, trying to go back to 0B1

**Comment by Lampornis** [comment] 2023-12-04 22:16
If you have a backup of your instance running 2023.12.0b1 you can do a total restore and you will be back in business.  Hopefully this gets fixed before Wednesday or I might have to dump DD.

Don

**Comment by FSHelgeland** [comment] 2023-12-04 23:10
Restored, and good for now.

**Comment by Lampornis** [comment] 2023-12-06 17:01
DD appears to work again in 2023.12.0b5.  Suspect we will be fine for today's release.

**Comment by FSHelgeland** [comment] 2023-12-06 22:38
Can you confirm it works in 2023.12.0 ? I am hesitating to install it unless I know. Dont want to do the work rolling back again.

**Comment by FrancoLoco** [comment] 2023-12-06 22:40
> Can you confirm it works in 2023.12.0 ? I am hesitating to install it unless I know. Dont want to do the work rolling back again.

Yes I can confirm it works in 2023.12.0

**Comment by Lampornis** [comment] 2023-12-07 00:27
Yes, it works fine with 2023.12.


Don & Theo Powers
24600 NE Hummingbird Ct
Newberg, OR 97132
503-550-1579
***@***.***

**Comment by Xander-V** [comment] 2023-12-10 14:07
In last Fridays HA:stable I get the following - I presume related - warning:

` Logger: homeassistant.helpers.frame
Source: helpers/frame.py:133
First occurred: December 9, 2023 at 23:54:57 (3 occurrences)
Last logged: December 9, 2023 at 23:55:04

    Detected that custom integration 'dwains_dashboard' uses deprecated 'SafeLineLoader' instead of 'PythonSafeLoader', which will stop working in HA Core 2024.6, at custom_components/dwains_dashboard/process_yaml.py, line 69: loader.SafeLineLoader.add_constructor("!include", _include_yaml), please create a bug report at https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues
    Detected that custom integration 'dwains_dashboard' uses deprecated 'SafeLineLoader' instead of 'PythonSafeLoader', which will stop working in HA Core 2024.6, at custom_components/dwains_dashboard/process_yaml.py, line 46: return loader.yaml.load(config_file, Loader=lambda stream: loader.SafeLineLoader(stream, secrets)) or OrderedDict(), please report it to the author of the 'dwains_dashboard' custom integration
    Detected that custom integration 'dwains_dashboard' uses deprecated 'SafeLineLoader' instead of 'PythonSafeLoader', which will stop working in HA Core 2024.6, at custom_components/dwains_dashboard/process_yaml.py, line 43: return loader.yaml.load(stream, Loader=lambda _stream: loader.SafeLineLoader(_stream, secrets)) or OrderedDict(), please report it to the author of the 'dwains_dashboard' custom integration
`

**Closed as completed** 2024-02-05 15:08 UTC

**Comment by barbatrukko** [comment] 2024-12-12 10:16
Hi @dwainscheeren , I have the same problem in 2024.12.X


```
2024-12-12 11:12:06.159 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/api/__init__.py", line 366, in get
    services = await async_services_json(request.app[KEY_HASS])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/api/__init__.py", line 507, in async_services_json
    descriptions = await async_get_all_descriptions(hass)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 745, in async_get_all_descriptions
    contents = await hass.async_add_executor_job(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        _load_services_files, hass, integrations
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 685, in _load_services_files
    return [_load_services_file(hass, integration) for integration in integrations]
            ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 664, in _load_services_file
    load_yaml_dict(str(integration.file_path / "services.yaml"))
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 186, in load_yaml_dict
    loaded_yaml = load_yaml(fname, secrets)
  File "/config/custom_components/dwains_dashboard/process_yaml.py", line 68, in load_yamll
    return loader.yaml.load(config_file, Loader=lambda stream: loader.SafeLineLoader(stream, secrets)) or OrderedDict()
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
  File "/config/custom_components/dwains_dashboard/process_yaml.py", line 68, in <lambda>
    return loader.yaml.load(config_file, Loader=lambda stream: loader.SafeLineLoader(stream, secrets)) or OrderedDict()
                                                               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.util.yaml.loader' has no attribute 'SafeLineLoader'

```

**Comment by PabloReyes** [comment] 2024-12-12 10:37
Same issue, still on 2024.12.X.

**Comment by Bekkie** [comment] 2025-01-05 12:16
Had the same issue on 2025.1.0 but with this fix: [replace SafeLineLoader to PythonSafeLoader](https://github.com/lockevod/dwains-lovelace-dashboard/pull/1/commits)
the problem is gone.

This DWAIN loading error prevented also to load the HA core automations to load, with appling the PythonSafeLoader fix the whole system was up and running again
