### ISSUE TITLE
HA Menu button not working on phone app

### ISSUE THREAD

**Issue by benixgil** [dwainscheeren/dwains-lovelace-dashboard#731] opened 2023-09-24 21:52 UTC
In the computer, everything works fine, but on the mobile app, the menu button of home assistant, so I can access the settings, hacs, automations, etc..., doesn't work. I press it, but nothing happens. Everything else is fine, but on the mobile I'm stock on dwainsdashboard.

**Comment by tseven** [comment] 2023-09-27 19:56
I'm experiencing the same issue.

**Comment by Calalei** [comment] 2023-09-28 22:36
I got similar issue that on Computer & iphone ok to open dwains dashboard but on Android phone & pad an error messages would appear .

**Comment by Calalei** [comment] 2023-09-28 22:36
![9e34290ddc804227bae173f7f97d7728](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/145919429/9138966f-4b5b-40ef-9db2-5dc5c7fd5c15)

**Comment by benixgil** [comment] 2023-09-29 17:11
Different problems. I'm only talking about the button to go to the side menu. The main HA menu.
Usually that problem you have is solved by cleaning the app cache. It solved when I had it.

**Comment by catatonico2** [comment] 2023-10-04 15:21
Same here

**Comment by j3ffrw** [comment] 2023-10-07 05:20
Same issue with me menu button in HA App doesn't work even after doing "Clear data" and "Clear cache" 
HA App 2023.9.2-full
DD 3.5.0(beta)
Android 13

**Comment by etvanp** [comment] 2023-10-07 09:05
Exact same issue, ha menu doesn't work. Any tips?

**Comment by Danigympie** [comment] 2023-10-10 08:34
I have the same issue but only on my Android phone. Iphone is working fine.

**Comment by husnainali09** [comment] 2023-10-10 10:09
Same issue

**Comment by ctqctq** [comment] 2023-10-10 18:18
The problem is that The dashboard depends on thomasloven/lovelace-card-tools to dispatch events to the root component. When I checked the function lovelace_view(), the root element is always null. So the events to open the menu never got to the component.

**Comment by husnainali09** [comment] 2023-10-12 12:10
Any fix for this yet. It's annoying

**Comment by xKronyx** [comment] 2023-10-13 12:31
same here onb android and iphone it doesn't work

**Comment by vitor-a-pinto-alb** [comment] 2023-10-13 14:35
one detail that might help @dwainscheeren 
If i'm using wifi on android, the menu bar appears on the top of screen of the mobile app and the menu button works. 
When using mobile data, the menu bar moves to the bottom and the menu button doesnt work. 

In the meanwhile as a workaround I set the homepage of the mobile App, for my user, to another dashboard, since the issue only happens on Dwains dashboard. At least this way I can always access the menu

**Comment by etvanp** [comment] 2023-10-13 14:36
one detail that might help @dwainscheeren 
If i'm using wifi on android, the menu bar appears on the top of screen of the mobile app and the menu button works. 
When using mobile data, the menu bar moves to the bottom and the menu button doesnt work.

**Comment by husnainali09** [comment] 2023-10-15 11:07
How far back do I need to downgrade to get back to normal ?

**Comment by lbouriez** [comment] 2023-10-18 23:41
Same on my pixel6

**Comment by Shenharo** [comment] 2023-10-19 06:10
What I did is add a button entity, set it as favorite so it will be accessible and change its card so it will navigate elsewhere.
Since this is annoying by itself I've edited the local dawin dashboard js file and made the HA menu visable as well(now I have both). The HA menu (look for the header class) works just fine so my next step is to remove the DD menu and test if it's still working.

**Comment by LordNex** [comment] 2023-10-19 21:13
Same issue here. I've also noticed that the previous versions I could still have the bar at the top. Now that it's at the bottom it's constantly in the way of buttons like submit. 

Additionally, it seems the only way I can get blueprints to actually show the drop down fields that need to be filled out is to Clear my cache, then reboot HA. After that it usually allows me to select the proper elements. But if you make a mistake. You can't re-edit the old page, you have to create a new one and do the whole clear cache reboot shuffle

Followed the proper procedures for updating from 3.4 to 3.5 which worked. But seems very buggy

**Comment by LordNex** [comment] 2023-10-19 21:14
> What I did is add a button entity, set it as favorite so it will be accessible and change its card so it will navigate elsewhere.
> 
> Since this is annoying by itself I've edited the local dawin dashboard js file and made the HA menu visable as well(now I have both). The HA menu (look for the header class) works just fine so my next step is to remove the DD menu and test if it's still working.

I'd love to see your procedures when you're done. I'd like my HA bar back and the DD bar at top.

**Comment by FuturamaPhill** [comment] 2023-10-20 20:23
Same issue here on android

**Comment by Grauwulf75** [comment] 2023-10-21 13:23
Also having the same issue on 3.5.0 on Android. Rolled back to 3.4.3, had to clear cache and app data after that to get it back to the top of the screen with the menu button working.

**Comment by Shenharo** [comment] 2023-10-21 17:33
> > What I did is add a button entity, set it as favorite so it will be accessible and change its card so it will navigate elsewhere.
> > Since this is annoying by itself I've edited the local dawin dashboard js file and made the HA menu visable as well(now I have both). The HA menu (look for the header class) works just fine so my next step is to remove the DD menu and test if it's still working.
> 
> I'd love to see your procedures when you're done. I'd like my HA bar back and the DD bar at top.

you can take a look here:
[](https://gist.github.com/Shenharo/1640bcdee4b14e945611e1f3f1bb34e0)
the thing is that I cant find a way to remove the DD menu only on mobile, so the desktop display isnt as pretty (its functional - but it also use the native HA menu) but it works for me (I mostly use mobile)
just replace the dwains-dashboard.js and the dwains-dashboard.js.gz if you want it.

what i did is replace the "display none" of the HA header with "display all" (e.shadowRoot.querySelector(".header").style.display="all") and remove the call to await this._buildDwainsNavigation(e)

**Comment by ISilvaPT** [comment] 2023-10-21 19:38
Same problem since 3.5.0 on mobile (chrome/Android).

**Comment by Drik78** [comment] 2023-10-22 01:22
I have the problem that the menu bar is not staying at the bottom of the screen on my mobile 
![IMG_0494](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/147914502/ec61f2fa-37a0-4780-bbef-055d37ec0584)

**Comment by husnainali09** [comment] 2023-10-22 02:39
@dwainscheeren Please could you take a few minutes out to fix this, making an otherwise great experience tiresome

**Comment by Woodham** [comment] 2023-10-22 16:17
Just set up Dwains Dashboard for the first time, everything went well but immediately hit this issue too - on Android the HA menu button in the bottom left doesn't work and so can't navigate back out of the dashboard.

**Comment by Shenharo** [comment] 2023-10-22 18:28
I've made the HA menu open on click (and moved it to the top since it was bugging me- but it isnt sticky).
here is the changed JS file.
[](https://gist.github.com/Shenharo/435dcc2e43202c1180eb6dcb3f39188b)
@dwainscheeren  -I've changed the menu toggle function to be: `document.querySelector('body > home-assistant').shadowRoot.querySelector('home-assistant-main').dispatchEvent(new CustomEvent('hass-toggle-menu', {detail: {open: true}}));` 
maybe you can use this solution?

**Comment by giveyouup** [comment] 2023-10-23 03:49
Same problem, was fine untill recent update

**Comment by ctqctq** [comment] 2023-10-23 04:18
> document.querySelector('body > home-assistant').shadowRoot.querySelector('home-assistant-main').dispatchEvent(new CustomEvent('hass-toggle-menu', {detail: {open: true}}));

Thank you very much, this is like the best fix so far. Very easy to do too.
Basically you just need to modify the `custom_components/dwains_dashboard/js/dwains-dashboard.js` file, look for `(0,a.B)("hass-toggle-menu")` and replace it with `document.querySelector('body > home-assistant').shadowRoot.querySelector('home-assistant-main').dispatchEvent(new CustomEvent('hass-toggle-menu', {detail: {open: true}}));`

Remember to rename dwains-dashboard.js.gz to something else, like "dwains-dashboard.js.gz.backup", so that the app uses the modified js file instead of the compressed gz.

**Comment by etvanp** [comment] 2023-10-23 08:17
@Shenharo thanks! This works. Maybe @dwainscheeren  can use this as the fix.

**Comment by dwainscheeren** [comment] 2023-10-25 09:08
Please try: https://github.com/dwainscheeren/dwains-lovelace-dashboard/releases/tag/v3.6.0 :)

**Comment by katter** [comment] 2023-10-25 12:12
Swipe Right from the very left works for me btw. (On 3.5.0)

**Comment by Solarflor** [comment] 2023-10-25 12:21
> I've changed the menu toggle function

How?

**Comment by etvanp** [comment] 2023-10-25 12:23
> Please try: https://github.com/dwainscheeren/dwains-lovelace-dashboard/releases/tag/v3.6.0 :)

I confirm its working! Thanks

**Comment by Solarflor** [comment] 2023-10-25 18:36
To not lost the current configuration I have copied the folder `dwains_dashboard` from v3.6.0 and copied into `custom_components` folder in HA replacing the old one.

But it doesnt work. I still have the same problem.

How I could replace 3.6.0 to 3.5.0. without to loose the configuration I have?

**Comment by ctqctq** [comment] 2023-10-25 19:23
> To not lost the current configuration I have copied the folder `dwains_dashboard` from v3.6.0 and copied into `custom_components` folder in HA replacing the old one.
> 
> But it doesnt work. I still have the same problem.
> 
> How I could replace 3.6.0 to 3.5.0. without to loose the configuration I have?

The configuration is in another folder, so even if you completely remove the integration and reinstall it, you should still have the current setup. The configure folder should be under /config/dwains-dashboard where you see the 2 folders "blueprints" and "configs".

**Comment by Shenharo** [comment] 2023-10-25 19:28
> Please try: https://github.com/dwainscheeren/dwains-lovelace-dashboard/releases/tag/v3.6.0 :)

Working. Thanks @dwainscheeren

**Comment by Solarflor** [comment] 2023-10-25 19:53
> remove the integration and reinstall it

I have removed the current integration but I'm not able to find the repository anymore in HACS.
How I could reinstall it?

**Comment by ghost** [comment] 2023-10-29 18:57
Please fix it, but only for admin users.
It's actually a good thing to be able to lock your wife and kids inside a dashboard. You can not imagine how much havoc an adhd wife and 2 boys around 10 can create in a ha setup 🤣
It might have started as a bug, but hell, it's a brilliant feature!

**Comment by Drik78** [comment] 2023-11-04 01:22
@dwainscheeren  I've installed 3.6, but it's not solving the issue with the menu that is not staying at the bottom,  #see my previous post
![277140667-ec61f2fa-37a0-4780-bbef-055d37ec0584](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/147914502/acd0721f-dc00-42dd-a4b1-81d553c17ed4)

**Comment by Solarflor** [comment] 2023-11-04 09:11
3.6 works well to me now 
![image](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/100423265/04ea3695-9cee-4cca-b7e0-1774bfecb068)

**Comment by ISilvaPT** [comment] 2023-11-04 18:27
> 3.6 works well to me now ![image](https://user-images.githubusercontent.com/100423265/280456908-04ea3695-9cee-4cca-b7e0-1774bfecb068.png)

Loking at your picture I'd say yours is the same as mine, meaning at the bottom (not working). You can access the menus from dwains dashboard but the HA menu is not working.  Won't expand up or down.

If I refresh the page and are fast enough I can click the HA menu, because upon refresh its still in the up position but 0.5s later it's moved down when the page finishes loading its relocated to the bottom. 

I have applied the beta 3.6 fix but the issue remains. Was fine in the previous version.

**Comment by Casuallynoted** [comment] 2023-11-14 05:49
Is there a way to have the menu on the top instead of the bottom?

**Comment by ghost** [comment] 2023-11-14 06:59
> Is there a way to have the menu on the top instead of the bottom?

A settings option would be nice

**Comment by nimdaxxx** [comment] 2023-12-03 17:03
I confirm the problem with v. 3.6.0. The menu is back at the bottom with companion apps (iPhone) and on Android tablet browsers (Fully Kiosk). I downgraded to v. 3.4.3 and the menu went back to the top. On Mac, companion apps and safari no problem.

**Comment by dwainscheeren** [comment] 2023-12-03 18:35
The menu on the bottom on mobile is where it needs to be :)

**Closed as completed by dwainscheeren** 2023-12-03 18:35 UTC

**Comment by nimdaxxx** [comment] 2023-12-03 20:53
Until v3.4.3 it was always at the top, even on iPhone :) Now I'm using v3.4.3 and the menu is at the top
![IMG_0035](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/98183781/64e0024d-7733-41a9-a6b3-43ec6238bde3)

**Comment by dwainscheeren** [comment] 2023-12-03 20:57
This was a bug in 3.4.3 the menu is since the start of DD at the bottom on mobile. It's be design put on bottom like other apps.

**Comment by nimdaxxx** [comment] 2023-12-03 21:01
Ok, so can you reinsert the bug in version 3.6.0? :D I find the menu at the top very convenient, especially on Kiosk tablets. Thank you for your work :)

**Comment by ISilvaPT** [comment] 2023-12-03 21:24
It's one of those things that should be optional. I think most of us use this dashboard for the ease of use and configurability, yet this very basic and fundamental function is hard-coded. 

Just an opinion 🤷.

**Comment by Casuallynoted** [comment] 2023-12-03 22:40
Big agree, I’d really prefer to have the option.

**Comment by nimdaxxx** [comment] 2023-12-03 23:23
> Big agree, I’d really prefer to have the option.

Let's hope @dwainscheeren gives us a Christmas present :)

**Comment by LordNex** [comment] 2023-12-04 00:59
Agreed 👍

**Comment by ghost** [comment] 2023-12-04 09:04
> It's one of those things that should be optional. I think most of us use this dashboard for the ease of use and configurability, yet this very basic and fundamental function is hard-coded.
> 
> Just an opinion 🤷.

in the app in landscape mode, both android and apple, the space where the top menu bar would be is not released. It's just a grey ribbon where the menu used to be. This makes the work area smaller, so in landscape mode it would be better to stick to top bar.

**Comment by nimdaxxx** [comment] 2023-12-04 11:57
> > It's one of those things that should be optional. I think most of us use this dashboard for the ease of use and configurability, yet this very basic and fundamental function is hard-coded.
> > Just an opinion 🤷.
> 
> in the app in landscape mode, both android and apple, the space where the top menu bar would be is not released. It's just a grey ribbon where the menu used to be. This makes the work area smaller, so in landscape mode it would be better to stick to top bar.

Exactly! That's what I forgot to point out.

**Comment by ghost** [comment] 2023-12-04 14:29
> > > It's one of those things that should be optional. I think most of us use this dashboard for the ease of use and configurability, yet this very basic and fundamental function is hard-coded.
> > > Just an opinion 🤷.
> > 
> > 
> > in the app in landscape mode, both android and apple, the space where the top menu bar would be is not released. It's just a grey ribbon where the menu used to be. This makes the work area smaller, so in landscape mode it would be better to stick to top bar.
> 
> Exactly! That's what I forgot to point out.

Same problem in portrait mode, actually. Just affects usability a bit less. If there was an option, I would set it to top menu right away, as it's more standard in HA.
E.g The energy card has a "see more" link to the energy dash and there it switches to top menu and that sticks so there will be top menu even in Dwain's.
Very confusing for the rest of the family.
Why fight it? Let's make due with top menu
Picture shows Dwain after return from energy dash and to confuse the crap out of users it returns to bottom menu again if you go back to main. 😂

![Screenshot_20231204-152226](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/129895762/a53ad8c2-7025-4a8a-8de3-521d259be32f)
