### ISSUE TITLE
Cannot add new blueprint

### ISSUE THREAD

**Issue by whoamicrypto** [dwainscheeren/dwains-lovelace-dashboard#643] opened 2022-11-03 17:16 UTC
Hi, I am trying to add a new page using the "create new page". 
Usually, on this site there is a field where to copy the YAML code.
This field is no longer visible ... so I cannot add new blueprints.
Any thoughts?

P.S. I am using the latest relaese of HA (2211) and DD3.3

**Comment by whoamicrypto** [comment] 2022-11-03 19:28
Just updated to Home Assistant Core 2022.11 version 01 ... problem seems to be fixed

**Comment by southwestflavorz** [comment] 2022-11-08 02:53
Currently I'm running a fresh install of 2022.11.01 and I'm still having the issue.

**Comment by pservais** [comment] 2022-11-08 08:45
Also running 2022.11.1 and sadly no field to insert yaml code

**Comment by robnnson** [comment] 2022-11-13 14:07
Also having same issue, with same versions of core/hassos/DD.

**Comment by yangtfu** [comment] 2022-11-20 09:04
Also having same issue, with same versions of core/hassos/DD.

**Comment by hsguyue** [comment] 2022-11-29 02:07
Also having same issue, with same versions of core/hassos/DD.

**Comment by oschmidteu** [comment] 2022-11-29 08:05
This is an duplicate of https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues/550
And Dwain is working on a fix https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues/550#issuecomment-1328013464

**Comment by pavolholes** [comment] 2023-01-09 14:27
Yes, duplicate, but the #550 is closed and not resolved. This one is opened so we can hope Dwain can track this one... Also it's a duplicate of [#106](https://github.com/dwainscheeren/dwains-dashboard-blueprints/issues/106) in Blueprints repo.

I've tried Firefox, Edge, two machines, nothing helps. At some point it was working and I was able to install one blueprint, but I don't know why it's not working again... AdBlock is disabled.

![image](https://user-images.githubusercontent.com/35877348/211331177-af167458-69f3-4aa2-b1f3-37ab0ac4fa02.png)

**Comment by fcolasuonno** [comment] 2023-01-12 10:59
I did a quick and dirty fix in my own branch here https://github.com/dwainscheeren/dwains-lovelace-dashboard/pull/667

**Comment by andystebbins** [comment] 2023-01-16 02:15
This brings it back for me.

Developer Tools>Services>Home Assistant Frontend: Reload themes.. Call service

**Comment by dwainscheeren** [comment] 2023-03-18 19:07
This problem is finally patched in v3.4.3 which will be released this weekend. You can now try it as beta https://github.com/dwainscheeren/dwains-lovelace-dashboard/tree/v3.4.3
I'm also working on a DD v4.0 which will be complete rewritten from scratch. Sponsoring people will get early access to an stable alpha version asap.  Take a look here to get access: https://github.com/sponsors/dwainscheeren

**Closed as completed by dwainscheeren** 2023-03-18 19:07 UTC
