### ISSUE TITLE
This entity (‘,’) does not have a unique ID

### ISSUE THREAD

**Issue by AlishaCl** [dwainscheeren/dwains-lovelace-dashboard#622] opened 2022-09-14 16:27 UTC
![FCB73DDD-77E6-4A89-99AF-3242A982C737](https://user-images.githubusercontent.com/113467506/190209071-63f998d0-7dc0-4ce0-b18b-b8a49caa905b.png)

I’m very new to HA, so please excuse my ignorance. I think this is going to be an amazing dashboard for my purposes, one of the group buttons at the top left of the dashboard (all fans or all lights, etc.) I get the pop up screen shown above with the error under the settings. What am I doing wrong?
Thanks!
Alisha

**Comment by shesmer** [comment] 2022-09-14 18:44
I am getting the same issue. It looks to me like it is caused because of this line in the JS code
`fireEvent("hass-more-info", {entityId: "."}, document.querySelector("home-assistant"));`

**Comment by dwainscheeren** [comment] 2022-09-14 19:41
Fix coming this week maximum sunday :)

**Comment by dwainscheeren** [comment] 2022-09-15 09:34
Duplicate of #619

**Closed as completed by dwainscheeren** 2022-09-15 09:34 UTC
