### ISSUE TITLE
Double popups bug in HA 2022.9

### ISSUE THREAD

**Issue by besiktas97** [dwainscheeren/dwains-lovelace-dashboard#619] opened 2022-09-07 20:47 UTC
I just have installed the new version of HA 2022.9.0.
When I press on the toolbar for which device is on or active I am getting a info tab instead of the devices:

![toolbar_dd](https://user-images.githubusercontent.com/76499056/188974930-d120a572-0814-46ac-9004-29f4a24c47df.png)

![Bug_DD](https://user-images.githubusercontent.com/76499056/188974975-7bcf0d23-7138-4087-a91c-119768f99031.png)

**Comment by HumongousFungus85** [comment] 2022-09-08 07:24
I am having the exact same problem! Also when I'm trying to edit the dashboard.

**Comment by Navarios** [comment] 2022-09-08 09:57
I am also experiencing the same issue right after the update to 2022.9

**Comment by WinkelB** [comment] 2022-09-08 10:06
Im having the same Problem
It's even worse on Mobile, the hole UI flickers

**Comment by EpsilonLima** [comment] 2022-09-08 11:48
Same problem for me as well after the update. 
Have the problem when trying to edit any of the items on the dashboard. 
It seems I can just dismiss the message box with the "." title and then make a change and it works, so I don't believe it is preventing anything from working (at least not that I have found). 
I also get the same box when saving the changes to any item on the dashboard.

**Comment by joeygithub1981** [comment] 2022-09-08 12:24
Same here 
![Uploading B30B80A3-B37F-40DB-947A-D9031E01F38A.png…]()

**Comment by thewazz1** [comment] 2022-09-08 19:18
An additional symptom I am seeing is that this also happens with any entity that I have assigned a pop up card to. For example on my Sonos’ I click on it and I get the more info card with the period in the title, I then X out of the more info and I then get my Sonos pop up card.

**Comment by tshan1229** [comment] 2022-09-08 23:05
Having the same issue.

**Comment by hrpaperstacks69** [comment] 2022-09-09 07:12
Upgraded to 2022.9.1. 

Still experiencing the same issue

**Comment by aidbish** [comment] 2022-09-09 07:38
> Upgraded to 2022.9.1.
> 
> Still experiencing the same issue

Upgrading to a newwer HA version wont fix it, the issue lies within the dashboard not HA

**Comment by wilqq-the** [comment] 2022-09-09 08:07
Same issue after upgrading to 2022.9.1 and newest DD.

**Comment by octvrium** [comment] 2022-09-09 18:21
> I just have installed the new version of HA 2022.9.0. When I press on the toolbar for which device is on or active I am getting a info tab instead of the devices:
> 
> ![toolbar_dd](https://user-images.githubusercontent.com/76499056/188974930-d120a572-0814-46ac-9004-29f4a24c47df.png)
> 
> ![Bug_DD](https://user-images.githubusercontent.com/76499056/188974975-7bcf0d23-7138-4087-a91c-119768f99031.png)

This window with the dot is the only thing is showing when you open the groups from main scree. Really annoying. Did someone found a workaround on this?

**Comment by besiktas97** [comment] 2022-09-09 19:11
Well its also opening when you press once on the toolbar. After that it keeps coming back, even when you press it away.

**Comment by octvrium** [comment] 2022-09-09 21:57
Just spoted following message: 
![image](https://user-images.githubusercontent.com/54385345/189451342-96e43599-c1f0-48e3-8bf2-4aebc8f274a7.png)

Is possible that current version is looking for this entity that doesn't exist

**Comment by defsix** [comment] 2022-09-10 09:44
I have the same issue when using the HA Android app or using Mobile browser.

I have this issue when trying to edit a  entity card. Also when selecting a chip for Switch or light. User chips work fine. 
![Screenshot_20220910-104141](https://user-images.githubusercontent.com/6899823/189477974-9404c1e3-1321-431f-abe2-e57ffd8920b5.png)

**Comment by dwainscheeren** [comment] 2022-09-10 11:16
Its a bug since 2022.9 for all users. I try to look into this this weekend.

**Comment by octvrium** [comment] 2022-09-14 02:41
> Its a bug since 2022.9 for all users. I try to look into this this weekend.

any news?

**Comment by octvrium** [comment] 2022-09-16 13:16
is possible to prevent this double pop up to be triggered? on mobile is almost impossible to access some windows because this "."windows take over the entire screen contrary to the web view where the real pop up get on the back greyed.

**Comment by znanywawa** [comment] 2022-09-16 20:15
> is possible to prevent this double pop up to be triggered? on mobile is almost impossible to access some windows because this "."windows take over the entire screen contrary to the web view where the real pop up get on the back greyed.

![image](https://user-images.githubusercontent.com/62244838/190725578-a2f9859f-05d8-406f-867e-6398f6d0562c.png)
So we have to wait unfortunately but we should keep fingers crossed :)

**Comment by dwainscheeren** [comment] 2022-09-16 20:22
Please try v3.3.0 its in pre-release available.

**Comment by philipp-kuttner** [comment] 2022-09-16 20:32
> Please try v3.3.0 its in pre-release available.

Hi,
unfortunately, the bug fix didn't help.

BR Philipp

**Comment by evildwarf90** [comment] 2022-09-16 20:32
> > Please try v3.3.0 its in pre-release available.
> 
> Hi, unfortunately, the bug fix didn't help.
> 
> BR Philipp

Have you cleared the cache after installing the update? For me it works.

**Comment by philipp-kuttner** [comment] 2022-09-16 20:33
> > > Please try v3.3.0 its in pre-release available.
> > 
> > 
> > Hi, unfortunately, the bug fix didn't help.
> > BR Philipp
> 
> Have you cleared the cache after installing the update? For me it works.

Oh yeah, this helps. Sorry for that!

**Comment by besiktas97** [comment] 2022-09-16 21:32
> Please try v3.3.0 its in pre-release available.

Thanks Dwain. Problem is solved for me!
Ps: on my phone iOS when I press for example the icon for lights it pops up with the lights with the choice turn them off. On my wallmounted iPad iOS the only things that pops up are the person cards and all the others like media player or light doesnt do anything. Cant also turn them off with the ipad when I click on it.

**Comment by silkw0rm** [comment] 2022-09-17 16:24
> > Please try v3.3.0 its in pre-release available.
> 
> Thanks Dwain. Problem is solved for me! Ps: on my phone iOS when I press for example the icon for lights it pops up with the lights with the choice turn them off. On my wallmounted iPad iOS the only things that pops up are the person cards and all the others like media player or light doesnt do anything. Cant also turn them off with the ipad when I click on it.

Same behavior for me as well, only person card actually opens. The rest does nothing. Running iOS 15.6.1 on iPhone 12

**Comment by MinBaoEr** [comment] 2022-09-17 16:58
Still same issue after updated to  V3.3 after clear all catch

**Comment by besiktas97** [comment] 2022-09-17 18:00
> Still same issue after updated to  V3.3 after clear all catch

If you are using the HA app you need to reset the front cache in the app.

**Comment by silkw0rm** [comment] 2022-09-17 19:01
> > Still same issue after updated to  V3.3 after clear all catch
> 
> If you are using the HA app you need to reset the front cache in the app.

Thanks, I’ve tried purging the front cache together with rebooting HA-server but unfortunately still same behavior in the iOS app.

**Comment by huysal89** [comment] 2022-09-17 19:25
Same on android device, update, force close, clear app cache. Unfortunately still same empty entity pop up :(

**Comment by tshan1229** [comment] 2022-09-17 19:27
Same as everyone else on Android. Installed beta version still not fixed. Thank you for your effort though we are patiently waiting for the fix 🙏

**Comment by znanywawa** [comment] 2022-09-18 12:27
Official 3.3.0 fixed mobile and web for me.
Thanks @dwainscheeren :)

But now I receive following error in logs:

This error originated from a custom integration.

```
Logger: custom_components.dwains_dashboard.sensor
Source: custom_components/dwains_dashboard/sensor.py:76
Integration: Dwains Dashboard (documentation, issues)
First occurred: 2:24:12 PM (1 occurrences)
Last logged: 2:24:12 PM

Dwains Dashboard version check failed TimeoutError()
```
@dwainscheeren, any idea?

**Comment by MinBaoEr** [comment] 2022-09-19 13:04
> > > Please try v3.3.0 its in pre-release available.
> > 
> > 
> > Thanks Dwain. Problem is solved for me! Ps: on my phone iOS when I press for example the icon for lights it pops up with the lights with the choice turn them off. On my wallmounted iPad iOS the only things that pops up are the person cards and all the others like media player or light doesnt do anything. Cant also turn them off with the ipad when I click on it.
> 
> Same behavior for me as well, only person card actually opens. The rest does nothing. Running iOS 15.6.1 on iPhone 12

my one is same as your one, windows web is on, but  IOS only people card have pop-up, others not working

**Comment by rubenmamo** [comment] 2022-09-20 06:58
I'm on 3.3.0 and still get the same issue both on Android and web ui

**Comment by besiktas97** [comment] 2022-09-20 07:47
> I'm on 3.3.0 and still get the same issue both on Android and web ui

You have deleted your cache of your browsers? If you are using the HA companion app, you need to reset the frontcache for it. I am also on the same version of you and it works. Except the point that I already gave above.

**Comment by MinBaoEr** [comment] 2022-09-20 08:14
> > I'm on 3.3.0 and still get the same issue both on Android and web ui
> 
> You have deleted your cache of your browsers? If you are using the HA companion app, you need to reset the frontcache for it. I am also on the same version of you and it works. Except the point that I already gave above.
Yes, My web UI is working, IOS after reset frontend, no pop up except people

**Comment by besiktas97** [comment] 2022-09-20 08:17
> > > I'm on 3.3.0 and still get the same issue both on Android and web ui
> > 
> > You have deleted your cache of your browsers? If you are using the HA companion app, you need to reset the frontcache for it. I am also on the same version of you and it works. Except the point that I already gave above.
> Yes, My web UI is working, IOS after reset frontend, no pop up except people 

Then the fix for the double pop-up is working, except for the no pop up for devices then only the people card. Thats also what I have mentioned before :-)

**Comment by rubenmamo** [comment] 2022-09-20 09:36
> > > > I'm on 3.3.0 and still get the same issue both on Android and web ui
> > > 
> > > 
> > > You have deleted your cache of your browsers? If you are using the HA companion app, you need to reset the frontcache for it. I am also on the same version of you and it works. Except the point that I already gave above.
> > > Yes, My web UI is working, IOS after reset frontend, no pop up except people
> 
> Then the fix for the double pop-up is working, except for the no pop up for devices then only the people card. Thats also what I have mentioned before :-)

I confirm the issue is sorted with the update. I mistook the **Dwains Dashboard Latest version** sensor as saying which is the latest installed version rather than the latest available version and didn't realise I was still on the old version. (facepalm)

**Comment by octvrium** [comment] 2022-09-20 14:05
After setting cache both are fixed. Thanks for the quick resolution. I love this dashboard.

On Sep 20, 2022, at 5:36 AM, Ruben Mamo ***@***.***> wrote:

﻿

I'm on 3.3.0 and still get the same issue both on Android and web ui

You have deleted your cache of your browsers? If you are using the HA companion app, you need to reset the frontcache for it. I am also on the same version of you and it works. Except the point that I already gave above.
Yes, My web UI is working, IOS after reset frontend, no pop up except people

Then the fix for the double pop-up is working, except for the no pop up for devices then only the people card. Thats also what I have mentioned before :-)

I confirm the issue is sorted with the update. I mistook the Dwains Dashboard Latest version sensor as saying which is the latest installed version rather than the latest available version and didn't realise I was still on the old version. (facepalm)

**Comment by davros123** [comment] 2022-09-21 01:03
Updated to 3.3.0 - works ok now on PC browser.

**Still not working correctly in iOS 15.6.1 Home Assistant App.**
Behavior: Click on People - works. Click on light (or switch or motion) does nothing. (button highlights with touch but no action/popup).
Reset Front End cache in debug menu.
Deleted app and all config.
Reinstall
Same issue

![image](https://user-images.githubusercontent.com/2758224/191391196-24b10360-f44b-4802-a0ab-d109adbab760.png)
![image](https://user-images.githubusercontent.com/2758224/191391770-88377a11-045f-4c26-85e6-e47b298a3de9.png)

**Comment by octvrium** [comment] 2022-09-21 02:34
Are you 100% sure you updated and also reset Hone Assistant?




On Sep 20, 2022, at 9:04 PM, davros123 ***@***.***> wrote:

﻿

Updated to 3.3.0 - works ok now on PC browser.

Still not working correctly in iOS 15.6.1 Home Assistant App.
Behavior: Click on People - works. Click on light (or switch or motion) does nothing. (button highlights with touch but no action/popup).
Reset Front End cache in debug menu.
Deleted app and all config.
Reinstall
Same issue

[image]<https://user-images.githubusercontent.com/2758224/191391196-24b10360-f44b-4802-a0ab-d109adbab760.png>

**Comment by MinBaoEr** [comment] 2022-09-21 02:38
> Updated to 3.3.0 - works ok now on PC browser.
> 
> 
> 
> **Still not working correctly in iOS 15.6.1 Home Assistant App.**
> 
> Behavior: Click on People - works. Click on light (or switch or motion) does nothing. (button highlights with touch but no action/popup).
> 
> Reset Front End cache in debug menu.
> 
> Deleted app and all config.
> 
> Reinstall
> 
> Same issue
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/2758224/191391196-24b10360-f44b-4802-a0ab-d109adbab760.png)
> 
> ![image](https://user-images.githubusercontent.com/2758224/191391770-88377a11-045f-4c26-85e6-e47b298a3de9.png)
> 
> 
> 
> 

Same issue as yours

**Comment by davros123** [comment] 2022-09-21 08:08
> Are you 100% sure you updated and also reset Hone Assistant? 

Yes :) I even did it again just now for you :) 
![image](https://user-images.githubusercontent.com/2758224/191450383-b8536497-c500-4bf8-9423-909fa531bfd3.png)

**Comment by dwainscheeren** [comment] 2022-09-22 12:53
Please click on the cog icon above the time on the homepage where you can set global settings, then click on Dashboard information and show me what you got there.

**Comment by besiktas97** [comment] 2022-09-22 12:55
> Please click on the cog icon above the time on the homepage where you can set global settings, then click on Dashboard information and show me what you got there.

Should be this:

![image](https://user-images.githubusercontent.com/76499056/191752706-e952d6f2-5992-4ba0-a8c0-b33c5573d634.png)

**Comment by davros123** [comment] 2022-09-23 01:10
Sure. 
![22-09-23 11-08-13 6116](https://user-images.githubusercontent.com/2758224/191875968-f5af25c9-315f-4f2c-b2aa-35bfbaa1b233.png)

**Comment by davros123** [comment] 2022-09-26 01:28
@dwainscheeren Do you need any more information to debug this issue ?

**Comment by MinBaoEr** [comment] 2022-09-26 01:35
> 
> 
> @dwainscheeren Do you need any more information to debug this issue ?

i have same issue as yours, I think only IOS have issue

**Comment by davros123** [comment] 2022-10-01 10:49
@dwainscheeren  any response?

**Comment by davros123** [comment] 2022-10-02 01:06
update: I upgraded my iOS to 16.0.2 and the issue went away. (As per suggestion in Discord from Dwain, )

**Comment by dwainscheeren** [comment] 2022-10-02 14:38
Thanks :)

**Closed as completed by dwainscheeren** 2022-10-02 14:38 UTC
Labels: bug
